import type { WorkflowGraph } from '../types';

export const overdueDuesWorkflow: WorkflowGraph = {
  schemaVersion: 1,
  id: 'example-overdue-dues',
  name: 'Overdue Dues Escalation',
  nodes: [
    { id: 'trigger-1', type: 'trigger', position: { x: 0, y: 260 }, data: { label: 'Dues overdue check', description: 'Nightly billing sweep' } },
    { id: 'condition-60', type: 'condition', position: { x: 240, y: 260 }, data: { label: 'Overdue > 60 days?', expression: 'member.dues_overdue_days > 60' } },
    { id: 'action-suspend', type: 'action', position: { x: 480, y: 80 }, data: { label: 'Suspend access', description: '' } },
    { id: 'action-notify-mgmt', type: 'action', position: { x: 720, y: 80 }, data: { label: 'Notify management', description: '' } },
    { id: 'condition-30', type: 'condition', position: { x: 480, y: 420 }, data: { label: 'Overdue > 30 days?', expression: 'member.dues_overdue_days > 30' } },
    { id: 'action-no-action', type: 'action', position: { x: 720, y: 560 }, data: { label: 'No action needed', description: '' } },
    { id: 'branch-remind', type: 'branch', position: { x: 720, y: 340 }, data: { label: 'Fan out reminders' } },
    { id: 'action-sms', type: 'action', position: { x: 960, y: 260 }, data: { label: 'Send SMS reminder', description: '' } },
    { id: 'action-email', type: 'action', position: { x: 960, y: 420 }, data: { label: 'Send email reminder', description: '' } },
    { id: 'merge-remind', type: 'merge', position: { x: 1200, y: 340 }, data: { label: 'Join reminders' } },
    { id: 'delay-7d', type: 'delay', position: { x: 1440, y: 340 }, data: { label: 'Wait 7 days', simulatedDuration: '7d', demoMs: 1200 } },
    { id: 'condition-recheck', type: 'condition', position: { x: 1680, y: 340 }, data: { label: 'Still overdue > 30 days?', expression: 'member.dues_overdue_days > 30' } },
    { id: 'action-escalate', type: 'action', position: { x: 1920, y: 260 }, data: { label: 'Escalate to collections', description: '' } },
    { id: 'action-resolved', type: 'action', position: { x: 1920, y: 420 }, data: { label: 'Mark resolved', description: '' } },
  ],
  edges: [
    { id: 'e1', source: 'trigger-1', target: 'condition-60' },
    { id: 'e2', source: 'condition-60', target: 'action-suspend', sourceHandle: 'true' },
    { id: 'e3', source: 'condition-60', target: 'condition-30', sourceHandle: 'false' },
    { id: 'e4', source: 'action-suspend', target: 'action-notify-mgmt' },
    { id: 'e5', source: 'condition-30', target: 'branch-remind', sourceHandle: 'true' },
    { id: 'e6', source: 'condition-30', target: 'action-no-action', sourceHandle: 'false' },
    { id: 'e7', source: 'branch-remind', target: 'action-sms' },
    { id: 'e8', source: 'branch-remind', target: 'action-email' },
    { id: 'e9', source: 'action-sms', target: 'merge-remind' },
    { id: 'e10', source: 'action-email', target: 'merge-remind' },
    { id: 'e11', source: 'merge-remind', target: 'delay-7d' },
    { id: 'e12', source: 'delay-7d', target: 'condition-recheck' },
    { id: 'e13', source: 'condition-recheck', target: 'action-escalate', sourceHandle: 'true' },
    { id: 'e14', source: 'condition-recheck', target: 'action-resolved', sourceHandle: 'false' },
  ],
};
